btre/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import url

urlpatterns = [
    path('', include('pages.urls')),
    path('rooms/', include('rooms.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rooms/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='rooms'),
    path('<int:room_id>', views.room, name='room'),
    path('search', views.search, name='search'),
]

rooms/models.py
from django.db import models
from datetime import datetime
from companies.models import Company


class Room(models.Model):
    HORROR = "HR"
    PUZZLE = "PE"
    COMEDY = "CY"
    POLICE = "PE"
    KIDS = "KS"
    CATEGORY_CHOICES = (
        (HORROR, "Horror"),
        (PUZZLE, "Puzzle"),
        (COMEDY, "Comedy"),
        (POLICE, "Police-Spy"),
        (KIDS, "Kids Friendly"),
    )
    DURATION_CHOICES = (
        ("60M", "60 Minutes"),
        ("70M", "70 Minutes"),
        ("80M", "80 Minutes"),
        ("90M", "90 Minutes"),
        ("90+M", "90+ Minutes"),
    )
    company = models.ForeignKey(Company, on_delete=models.DO_NOTHING)
    title = models.CharField(max_length=200)
    difficulty = models.CharField(max_length=50)
    category = models.CharField(
        max_length=3, choices=CATEGORY_CHOICES, default="CY")
    duration = models.CharField(
        max_length=5, choices=DURATION_CHOICES, default="60M")
    description = models.TextField(blank=True)
    photo_main = models.ImageField(upload_to='photos/%Y/%m/%d/')
    photo_1 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_2 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_3 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_4 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_5 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    photo_6 = models.ImageField(upload_to='photos/%Y/%m/%d/', blank=True)
    is_published = models.BooleanField(default=True)
    list_date = models.DateTimeField(default=datetime.now, blank=True)

    def __str__(self):
        return self.title

rooms/views.py
from django.shortcuts import get_object_or_404, render
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator

from .models import Room


def index(request):
    rooms = Room.objects.order_by('-list_date').filter(is_published=True)
    category_choices = Room.CATEGORY_CHOICES
    duration_choices = Room.DURATION_CHOICES

    paginator = Paginator(rooms, 6)
    page = request.GET.get('page')
    paged_rooms = paginator.get_page(page)

    context = {
        'rooms': paged_rooms
    }

    return render(request, 'rooms/rooms.html', context)


def room(request, room_id):
    room = get_object_or_404(Room, pk=room_id)
    ratings = {
        'item': 3
    }

    context = {
        'room': room,
        'ratings': ratings
    }

    return render(request, 'rooms/room.html', context)


def search(request):
    queryset_list = Room.objects.order_by('-list_date')

    # Keywords
    if 'keywords' in request.GET:
        keywords = request.GET['keywords']
        if keywords:
            queryset_list = queryset_list.filter(
                description__icontains=keywords)

    # City
    if 'city' in request.GET:
        city = request.GET['city']
        # if city:
            # queryset_list = queryset_list.filter(city__iexact=city)

    # Category
    if 'category' in request.GET:
        category = request.GET['category']
        if category:
            queryset_list = queryset_list.filter(category__iexact=category)

    # Duration
    if 'duration' in request.GET:
        duration = request.GET['duration']
        if duration:
            queryset_list = queryset_list.filter(duration__iexact=duration)

    category_choices = Room.CATEGORY_CHOICES
    duration_choices = Room.DURATION_CHOICES
    context = {
        'category_choices': category_choices,
        'duration_choices': duration_choices,
        'rooms': queryset_list,
        'values': request.GET
    }
    
    return render(request, 'rooms/search.html', context)

templates/rooms/room.html
{% extends 'base.html' %} 

{% block title %} | {{ room.title }} {% endblock %}

{% load humanize %}



{% block content %}

<section id="showcase-inner" class="py-5 text-white">
  <div class="container">
    <div class="row text-center">
      <div class="col-md-12">
        <h1 class="display-4">{{ room.title }}</h1>
        <p class="lead">{{ room.company }}</p>
        
      </div>
    </div>
  </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
  <div class="container">
    <nav>
      <ol class="breadcrumb">
        <li class="breadcrumb-item"><a href="{% url 'index' %}">Home</a></li>
        <li class="breadcrumb-item"><a href="{% url 'rooms' %}">Rooms</a></li>
        <li class="breadcrumb-item active">{{ room.title }}</li>
      </ol>
    </nav>
  </div>
</section>

<!-- Listing -->
<section id="listing" class="py-4">
  <div class="container">
    <a href="{% url 'rooms' %}" class="btn btn-light mb-4">Back To Rooms</a>
    <div class="row">
      <div class="col-md-9">
        <!-- Home Main Image -->
        <img
          src="{{ room.photo_main.url }}"
          alt=""
          class="img-main img-fluid mb-3"
        />
        <!-- Thumbnails -->

        <div class="row mb-5 thumbs">
          {% if room.photo_1 %}
          <div class="col-md-2">
            <a href="{{ room.photo_1.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_1.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if room.photo_2 %}
          <div class="col-md-2">
            <a href="{{ room.photo_2.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_2.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if room.photo_3 %}
          <div class="col-md-2">
            <a href="{{ room.photo_3.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_3.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if room.photo_4 %}
          <div class="col-md-2">
            <a href="{{ room.photo_4.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_4.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if room.photo_5 %}
          <div class="col-md-2">
            <a href="{{ room.photo_5.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_5.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %} {% if room.photo_6 %}
          <div class="col-md-2">
            <a href="{{ room.photo_6.url }}" data-lightbox="home-images">
              <img src="{{ room.photo_6.url }}" alt="" class="img-fluid" />
            </a>
          </div>
          {% endif %}
        </div>
        <!-- Fields -->
        <div class="row mb-5 fields">
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                Name: <span class="float-right">{{ room.title }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Duration: <span class="float-right">{{ room.get_duration_display }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Difficulty:
                <span class="float-right">{{ room.difficulty }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Category: <span class="float-right">{{ room.get_category_display }}</span>
              </li>
            </ul>
          </div>
          <div class="col-md-6">
            <ul class="list-group list-group-flush">
              <li class="list-group-item text-secondary">
                <i class="fas fa-calendar"></i> Listing Date:
                <span class="float-right">{{ room.list_date }}</span>
              </li>
              <li class="list-group-item text-secondary">
                Company: <span class="float-right">{{ room.company }}</span>
              </li>
            </ul>
          </div>
        </div>

        <!-- Description -->
        <div class="row mb-5">
          <div class="col-md-12">{{ room.description }}</div>
        </div>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/rooms/rooms.html
{% extends 'base.html' %}

{% block title %} | Browse Rooms {% endblock %}

{% block content %}

<!-- Rooms -->
<section id="rooms" class="py-4">
    <div class="container">
        <div class="row">
            {% if rooms %}
            {% for room in rooms %}
            <!-- Listing 1 -->

            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                    <img class="projectIcon" src="{{ room.photo_main.url }}" alt="" style="height: 180px; width: 100%;">
                    <div class="card-body">
                        <div class="listing-heading text-center">
                            <h4 class="text-primary">{{ room.title }}</h4>
                            <p>
                                {{ room.company }}
                            </p>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Difficulty: {{ room.difficulty }}
                            </div>
                        </div>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Duration: {{ room.get_duration_display }}
                            </div>
                        </div>
                        <div class="row text-secondary pb-2">
                            <div class="col-12">
                                Category: {{ room.get_category_display }}
                            </div>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Users rating: 5 stars
                            </div>
                        </div>

                        <hr>
                        <a href="{% url 'room' room.id %}" class="btn btn-primary btn-block">More Info</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>No Rooms Available</p>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-12">
                {% if rooms.has_other_pages %}
                <ul class="pagination justify-content-center">
                    {% if rooms.has_previous %}
                    <li class="page-item">
                        <a href="?page={{rooms.previous_page_number}}" class="page-link">
                            &laquo;
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            &laquo;
                        </a>
                    </li>
                    {% endif %}
                    {% for i in rooms.paginator.page_range %}
                    {% if rooms.number == i %}
                    <li class="page-item active">
                        <a class="page-link">
                            {{i}}
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{i}}" class="page-link">
                            {{i}}
                        </a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if rooms.has_next %}
                    <li class="page-item">
                        <a href="?page={{rooms.next_page_number}}" class="page-link">
                            &raquo;
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            &raquo;
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>

</section>

{% endblock %}

templates/rooms/search.html
{% extends 'base.html' %}

{% block title %} | Search Results {% endblock %}

{% block content %}

<section id="showcase-inner" class="showcase-search text-white py-5">
    <div class="container">
        <div class="row text-center">
            <div class="col-md-12">

                <form action="{% url 'search' %}">
                    <!-- Form Row 1 -->
                    <div class="form-row">
                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Keywords</label>
                            <input type="text" name="keywords" class="form-control" placeholder="Keyword" value="{{ values.keywords }}" />
                        </div>

                        <div class="col-md-4 mb-3">
                            <label class="sr-only">City</label>
                            <input type="text" name="city" class="form-control" placeholder="City" value="{{ values.city }}" />
                        </div>

                        <div class="col-md-4 mb-3">
                            <label class="sr-only">Category</label>
                            <select name="category" class="form-control">
                                <option selected="true" disabled="disabled">Category (All)</option>
                                {% for key, value in category_choices %}
                                <option value="{{ key }}"
                                {% if key == values.category %}
                                    selected
                                {% endif %}
                                >{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <!-- Form Row 2 -->
                    <div class="form-row">
                        <div class="col-md mb-3">
                            <label class="sr-only">Duration</label>
                            <select name="duration" class="form-control">
                                {% for key, value in duration_choices %}
                                <option value="{{ key }}"
                                {% if key == values.duration %}
                                    selected
                                {% endif %}
                                >{{ value }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <button class="btn btn-outline-light btn-block mt-4" type="submit">
                        Search
                    </button>
                </form>
            </div>
        </div>

    </div>
</section>

<!-- Breadcrumb -->
<section id="bc" class="mt-3">
    <div class="container">
        <nav aria-label="breadcrumb">
            <ol class="breadcrumb">
                <li class="breadcrumb-item">
                    <a href="{% url 'index' %}">
                        <i class="fas fa-home"></i> Home</a>
                </li>
                <li class="breadcrumb-item">
                    <a href="{% url 'rooms' %}">Browse Rooms</a>
                </li>
                <li class="breadcrumb-item active"> Search Results</li>
            </ol>
        </nav>
    </div>
</section>

<!-- Rooms -->
<section id="rooms" class="py-4">
    <div class="container">
        <div class="row">
            {% if rooms %}
            {% for room in rooms %}
            <!-- Listing 1 -->

            <div class="col-md-6 col-lg-4 mb-4">
                <div class="card listing-preview">
                    <img class="projectIcon" src="{{ room.photo_main.url }}" alt="" style="height: 180px; width: 100%;">
                    <div class="card-body">
                        <div class="listing-heading text-center">
                            <h4 class="text-primary">{{ room.title }}</h4>
                            <p>
                                {{ room.company }}
                            </p>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Difficulty: {{ room.difficulty }}
                            </div>
                        </div>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Duration: {{ room.get_duration_display }}
                            </div>
                        </div>
                        <div class="row text-secondary pb-2">
                            <div class="col-12">
                                Category: {{ room.get_category_display }}
                            </div>
                        </div>
                        <hr>
                        <div class="row py-2 text-secondary">
                            <div class="col-12">
                                Users rating: 5 stars
                            </div>
                        </div>

                        <hr>
                        <a href="{% url 'room' room.id %}" class="btn btn-primary btn-block">More Info</a>
                    </div>
                </div>
            </div>
            {% endfor %}
            {% else %}
            <div class="col-md-12">
                <p>No Rooms Available</p>
            </div>
            {% endif %}
        </div>

        <div class="row">
            <div class="col-md-12">
                {% if rooms.has_other_pages %}
                <ul class="pagination justify-content-center">
                    {% if rooms.has_previous %}
                    <li class="page-item">
                        <a href="?page={{rooms.previous_page_number}}" class="page-link">
                            &laquo;
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            &laquo;
                        </a>
                    </li>
                    {% endif %}
                    {% for i in rooms.paginator.page_range %}
                    {% if rooms.number == i %}
                    <li class="page-item active">
                        <a class="page-link">
                            {{i}}
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item">
                        <a href="?page={{i}}" class="page-link">
                            {{i}}
                        </a>
                    </li>
                    {% endif %}
                    {% endfor %}
                    {% if rooms.has_next %}
                    <li class="page-item">
                        <a href="?page={{rooms.next_page_number}}" class="page-link">
                            &raquo;
                        </a>
                    </li>
                    {% else %}
                    <li class="page-item disabled">
                        <a class="page-link">
                            &raquo;
                        </a>
                    </li>
                    {% endif %}
                </ul>
                {% endif %}
            </div>
        </div>

</section>

{% endblock %}